#!/bin/sh

cd "$(dirname "$(realpath "$0")")/../" || exit 255

NAMES_FILE="src/lib/ui/fontawesome/generated.ts"

echo "Generating FontAwesome names..."

{
    cat << EOF
// WARNING:
// This file is automatically generated.
// Do not edit manually.

EOF

    echo "export const BrandIconNames = ["
    tail -n +20 public/assets/fontawesome/css/brands.css | grep '^.fa-' | awk '{ print $1 }' | cut -f1 -d: | cut -f2- -d'-' | sort | xargs -I% echo "    '%',"
    echo "]"

    echo ""

    echo "export const SolidIconNames = ["
    tail -n +333 public/assets/fontawesome/css/fontawesome.css | grep '^.fa-' | awk '{ print $1 }' | cut -f1 -d: | cut -f2- -d'-' | sort | xargs -I% echo "    '%',"
    echo "]"

    echo ""
} > "${NAMES_FILE}" \
    && pnpm exec eslint --fix "${NAMES_FILE}" \
    && pnpm exec prettier -w "${NAMES_FILE}"
