#!/bin/sh

cd "$(dirname "$(realpath "$0")")/../" || exit 255

TYPES_FILE="src/types/fontawesome/generated.ts"

(
    cat << EOF
// WARNING:
// This file is automatically generated.
// Do not edit manually.

EOF

    echo "export type FAB ="
    tail -n +20 public/assets/fontawesome/css/brands.css | grep '^.fa-' | awk '{ print $1 }' | cut -f1 -d: | cut -f2- -d'-' | sort | xargs -I% echo "    | '%'"

    echo ""

    echo "export type FAS ="

    tail -n +333 public/assets/fontawesome/css/fontawesome.css | grep '^.fa-' | awk '{ print $1 }' | cut -f1 -d: | cut -f2- -d'-' | sort | xargs -I% echo "    | '%'"

    echo ""

    echo "export type IconName = FAB | FAS"

    echo""
) > "${TYPES_FILE}" \
    && pnpm exec eslint --fix "${TYPES_FILE}" \
    && pnpm exec prettier -w "${TYPES_FILE}"
