#!/bin/sh

TRACKING_FILES="src/lib/validators/common.ts src/lib/validators/records.ts"

cd "$(dirname "$(realpath "$0")")/../" || exit 255

OUTPUT_FILES="./src/lib/validators/guards.ts"
VALIDATORS="common records"

echo "Generating types..."
for VALIDATOR in ${VALIDATORS}; do
    VALIDATOR_FILE="./src/lib/validators/${VALIDATOR}.ts"
    VALIDATOR_IMPORT="@/lib/validators/${VALIDATOR}.ts"
    TYPE_FILE="./src/types/validators/${VALIDATOR}.ts"

    {
        cat << EOF
// WARNING:
// This file is automatically generated.
// Do not edit manually.

import type { z } from 'zod'

EOF
        echo "import { $(grep 'export const z' "${VALIDATOR_FILE}" | awk '{ print $3 }' | sort | xargs | tr ' ' ',')} from '${VALIDATOR_IMPORT}'"
        grep 'export const z' "${VALIDATOR_FILE}" \
            | awk '{ print $3 }' \
            | cut -c2- \
            | sort \
            | while read -r VALIDATOR_FN; do
                echo ""
                echo "${VALIDATOR_FN}" | xargs -I% echo -e "export type % = z.infer<typeof z%>"
                if [ "$(echo "${VALIDATOR_FN}" | grep -E 's$')" = "" ]; then
                    echo "${VALIDATOR_FN}" | xargs -I% echo -e "export type %s = %[]"
                fi
            done
    } > "${TYPE_FILE}"

    OUTPUT_FILES="${OUTPUT_FILES} ${TYPE_FILE}"
done

echo "Generating guards..."
{
    cat << EOF
// WARNING:
// This file is automatically generated.
// Do not edit manually.

EOF
    echo "import { $(grep 'export type ' src/types/validators/common.ts | awk '{ print $3 }' | xargs | tr ' ' ',')} from '@/types/validators/common'"
    echo "import { $(grep 'export type ' src/types/validators/records.ts | awk '{ print $3 }' | xargs | tr ' ' ',')} from '@/types/validators/records'"
    echo "import { $(grep 'export type ' src/types/validators/common.ts | grep -v -E '\[\]' | awk '{ print "z" $3 }' | sort | xargs | tr ' ' ',')} from '@/lib/validators/common'"
    echo "import { $(grep 'export type ' src/types/validators/records.ts | grep -v -E '\[\]' | awk '{ print "z" $3 }' | sort | xargs | tr ' ' ',')} from '@/lib/validators/records'"
    cat ./src/types/validators/records.ts ./src/types/validators/common.ts \
        | grep 'export type' \
        | grep -v -E '\[\]' \
        | awk '{ print $3 }' \
        | sort \
        | grep -v 'BaseFields' \
        | while read -r VALIDATOR_FN; do
            echo ""
            echo "${VALIDATOR_FN}" | xargs -I% echo -e 'export const is% = (inp: unknown): inp is % => z%.safeParse(inp).success'
            if [ "$(echo "${VALIDATOR_FN}" | grep -E 's$')" = "" ]; then
                echo "${VALIDATOR_FN}" | xargs -I% echo -e 'export const is%s = (inp: unknown): inp is %s => z%.array().safeParse(inp).success'
            fi
        done

} > ./src/lib/validators/guards.ts

# shellcheck disable=SC2086
echo "Formatting output files..." \
    && pnpm exec eslint --fix ${OUTPUT_FILES} \
    && pnpm exec prettier -w ${OUTPUT_FILES}

# shellcheck disable=SC2086
if [ "$(git status -s ${TRACKING_FILES} | grep -E '^M')" != "" ]; then
    echo "Detected staged tracking files. Adding modified files..."
    git add ${OUTPUT_FILES}
fi
