#!/bin/sh

cd "$(dirname "$(realpath "$0")")/../" || exit 255

{
    cat << EOF
// WARNING:
// This file is automatically generated.
// Do not edit manually.

EOF
    echo "import { $(grep 'export const z' ./src/lib/validators/common.ts | awk '{ print $3 }' | cut -c2- | sort | xargs | tr ' ' ',')} from '@/types/common'"
    echo "import { $(grep 'export const z' ./src/lib/validators/records.ts | awk '{ print $3 }' | cut -c2- | sort | xargs | tr ' ' ',')} from '@/types/records'"
    echo "import { $(grep 'export const z' ./src/lib/validators/common.ts | awk '{ print $3 }' | sort | xargs | tr ' ' ',')} from '@/lib/validators/common'"
    echo "import { $(grep 'export const z' ./src/lib/validators/records.ts | awk '{ print $3 }' | sort | xargs | tr ' ' ',')} from '@/lib/validators/records'"
    echo ""
    cat ./src/lib/validators/records.ts ./src/lib/validators/common.ts | grep 'export const z' | awk '{ print $3 }' | cut -c2- | sort | xargs -I% echo 'export const is% = (inp: unknown): inp is % => z%.safeParse(inp).success'
} > ./src/lib/validators/guards.ts && pnpm exec eslint --fix ./src/lib/validators/guards.ts && pnpm exec prettier -w ./src/lib/validators/guards.ts
