// WARNING:
// This file is automatically generated.
// Do not edit manually.

import {
    zBoolean,
    zBooleanRecord,
    zBooleanRecords,
    zBooleans,
    zCoerceNumber,
    zCoerceNumbers,
    zCoerceString,
    zCoerceStrings,
    zDateTime,
    zDateTimeFormInput,
    zDateTimeFormInputs,
    zDateTimes,
    zDateTimeString,
    zDateTimeStrings,
    zEmailAddress,
    zEmailAddresss,
    zEmptyArray,
    zEmptyOrMinString,
    zEmptyOrMinStrings,
    zFunctionBoolResultFromStringArraySpread,
    zFunctionBoolResultFromStringArraySpreads,
    zHTTPMethod,
    zHTTPMethods,
    zHumanName,
    zHumanNames,
    zIpnValidationState,
    zIpnValidationStates,
    zKeyType,
    zKeyTypes,
    zMinString,
    zMinStrings,
    zMoneyBookers,
    zMoneyBookerss,
    zNonEmptyStrings,
    zNonNegativeNumber,
    zNonNegativeNumbers,
    zNumber,
    zNumberRecord,
    zNumbers,
    zNumberStringRecord,
    zPasswordField,
    zPasswordFields,
    zPasswordInput,
    zPasswordInputs,
    zPaymentProvider,
    zPaymentProviders,
    zPayPal,
    zPayPals,
    zPositiveNumber,
    zPositiveNumbers,
    zSpreadString,
    zSpreadStrings,
    zString,
    zStringRecord,
    zStringRecords,
    zStrings,
    zStringStringRecord,
    zStringStringRecords,
    zStripe,
    zStripePaymentState,
    zStripePaymentStates,
    zStripes,
    zUnknown,
    zUrl,
    zUrls,
    zUserActiveState,
    zUserActiveStateCode,
    zUserActiveStateCodes,
    zUserActiveStates,
    zUserActiveStateTitle,
    zUserActiveStateTitles,
    zUserActiveStateType,
    zUserActiveStateTypes,
    zUserActiveStatus,
    zUserActiveStatuses,
    zUserBannedStateType,
    zUserBannedStateTypes,
    zUserInactiveStateType,
    zUserInactiveStateTypes,
    zUsername,
    zUsernames,
    zUserPendingStateType,
    zUserPendingStateTypes,
    zUserPin,
    zUserPins,
    zUserStateCodeActive,
    zUserStateCodeActives,
    zUserStateCodeBanned,
    zUserStateCodeBanneds,
    zUserStateCodeInactive,
    zUserStateCodeInactives,
    zUserStateCodePending,
    zUserStateCodePendings,
    zUserStateTitleActive,
    zUserStateTitleActives,
    zUserStateTitleBanned,
    zUserStateTitleBanneds,
    zUserStateTitleInactive,
    zUserStateTitleInactives,
    zUserStateTitlePending,
    zUserStateTitlePendings
} from '@/lib/validators/common.ts'

import type {
    Boolean,
    BooleanRecord,
    BooleanRecords,
    Booleans,
    CoerceNumber,
    CoerceNumbers,
    CoerceString,
    CoerceStrings,
    DateTime,
    DateTimeFormInput,
    DateTimeFormInputs,
    DateTimes,
    DateTimeString,
    DateTimeStrings,
    EmailAddress,
    EmailAddresss,
    EmptyArray,
    EmptyOrMinString,
    EmptyOrMinStrings,
    FunctionBoolResultFromStringArraySpread,
    FunctionBoolResultFromStringArraySpreads,
    HTTPMethod,
    HTTPMethods,
    HumanName,
    HumanNames,
    IpnValidationState,
    IpnValidationStates,
    KeyType,
    KeyTypes,
    MinString,
    MinStrings,
    MoneyBookers,
    MoneyBookerss,
    NonEmptyStrings,
    NonNegativeNumber,
    NonNegativeNumbers,
    Number,
    NumberRecord,
    Numbers,
    NumberStringRecord,
    PasswordField,
    PasswordFields,
    PasswordInput,
    PasswordInputs,
    PaymentProvider,
    PaymentProviders,
    PayPal,
    PayPals,
    PositiveNumber,
    PositiveNumbers,
    SpreadString,
    SpreadStrings,
    String,
    StringRecord,
    StringRecords,
    Strings,
    StringStringRecord,
    StringStringRecords,
    Stripe,
    StripePaymentState,
    StripePaymentStates,
    Stripes,
    Unknown,
    Url,
    Urls,
    UserActiveState,
    UserActiveStateCode,
    UserActiveStateCodes,
    UserActiveStates,
    UserActiveStateTitle,
    UserActiveStateTitles,
    UserActiveStateType,
    UserActiveStateTypes,
    UserActiveStatus,
    UserActiveStatuses,
    UserBannedStateType,
    UserBannedStateTypes,
    UserInactiveStateType,
    UserInactiveStateTypes,
    Username,
    Usernames,
    UserPendingStateType,
    UserPendingStateTypes,
    UserPin,
    UserPins,
    UserStateCodeActive,
    UserStateCodeActives,
    UserStateCodeBanned,
    UserStateCodeBanneds,
    UserStateCodeInactive,
    UserStateCodeInactives,
    UserStateCodePending,
    UserStateCodePendings,
    UserStateTitleActive,
    UserStateTitleActives,
    UserStateTitleBanned,
    UserStateTitleBanneds,
    UserStateTitleInactive,
    UserStateTitleInactives,
    UserStateTitlePending,
    UserStateTitlePendings
} from '@/types/validators/common.ts'

export const isBoolean = (inp: unknown): inp is Boolean => zBoolean.safeParse(inp).success

export const isBooleanRecord = (inp: unknown): inp is BooleanRecord => zBooleanRecord.safeParse(inp).success

export const isBooleanRecords = (inp: unknown): inp is BooleanRecords => zBooleanRecords.safeParse(inp).success

export const isBooleans = (inp: unknown): inp is Booleans => zBooleans.safeParse(inp).success

export const isCoerceNumber = (inp: unknown): inp is CoerceNumber => zCoerceNumber.safeParse(inp).success

export const isCoerceNumbers = (inp: unknown): inp is CoerceNumbers => zCoerceNumbers.safeParse(inp).success

export const isCoerceString = (inp: unknown): inp is CoerceString => zCoerceString.safeParse(inp).success

export const isCoerceStrings = (inp: unknown): inp is CoerceStrings => zCoerceStrings.safeParse(inp).success

export const isDateTime = (inp: unknown): inp is DateTime => zDateTime.safeParse(inp).success

export const isDateTimeFormInput = (inp: unknown): inp is DateTimeFormInput => zDateTimeFormInput.safeParse(inp).success

export const isDateTimeFormInputs = (inp: unknown): inp is DateTimeFormInputs =>
    zDateTimeFormInputs.safeParse(inp).success

export const isDateTimes = (inp: unknown): inp is DateTimes => zDateTimes.safeParse(inp).success

export const isDateTimeString = (inp: unknown): inp is DateTimeString => zDateTimeString.safeParse(inp).success

export const isDateTimeStrings = (inp: unknown): inp is DateTimeStrings => zDateTimeStrings.safeParse(inp).success

export const isEmailAddress = (inp: unknown): inp is EmailAddress => zEmailAddress.safeParse(inp).success

export const isEmailAddresss = (inp: unknown): inp is EmailAddresss => zEmailAddresss.safeParse(inp).success

export const isEmptyArray = (inp: unknown): inp is EmptyArray => zEmptyArray.safeParse(inp).success

export const isEmptyOrMinString = (inp: unknown): inp is EmptyOrMinString => zEmptyOrMinString.safeParse(inp).success

export const isEmptyOrMinStrings = (inp: unknown): inp is EmptyOrMinStrings => zEmptyOrMinStrings.safeParse(inp).success

export const isFunctionBoolResultFromStringArraySpread = (
    inp: unknown
): inp is FunctionBoolResultFromStringArraySpread => zFunctionBoolResultFromStringArraySpread.safeParse(inp).success

export const isFunctionBoolResultFromStringArraySpreads = (
    inp: unknown
): inp is FunctionBoolResultFromStringArraySpreads => zFunctionBoolResultFromStringArraySpreads.safeParse(inp).success

export const isHTTPMethod = (inp: unknown): inp is HTTPMethod => zHTTPMethod.safeParse(inp).success

export const isHTTPMethods = (inp: unknown): inp is HTTPMethods => zHTTPMethods.safeParse(inp).success

export const isHumanName = (inp: unknown): inp is HumanName => zHumanName.safeParse(inp).success

export const isHumanNames = (inp: unknown): inp is HumanNames => zHumanNames.safeParse(inp).success

export const isIpnValidationState = (inp: unknown): inp is IpnValidationState =>
    zIpnValidationState.safeParse(inp).success

export const isIpnValidationStates = (inp: unknown): inp is IpnValidationStates =>
    zIpnValidationStates.safeParse(inp).success

export const isKeyType = (inp: unknown): inp is KeyType => zKeyType.safeParse(inp).success

export const isKeyTypes = (inp: unknown): inp is KeyTypes => zKeyTypes.safeParse(inp).success

export const isMinString = (inp: unknown): inp is MinString => zMinString.safeParse(inp).success

export const isMinStrings = (inp: unknown): inp is MinStrings => zMinStrings.safeParse(inp).success

export const isMoneyBookers = (inp: unknown): inp is MoneyBookers => zMoneyBookers.safeParse(inp).success

export const isMoneyBookerss = (inp: unknown): inp is MoneyBookerss => zMoneyBookerss.safeParse(inp).success

export const isNonEmptyStrings = (inp: unknown): inp is NonEmptyStrings => zNonEmptyStrings.safeParse(inp).success

export const isNonNegativeNumber = (inp: unknown): inp is NonNegativeNumber => zNonNegativeNumber.safeParse(inp).success

export const isNonNegativeNumbers = (inp: unknown): inp is NonNegativeNumbers =>
    zNonNegativeNumbers.safeParse(inp).success

export const isNumber = (inp: unknown): inp is Number => zNumber.safeParse(inp).success

export const isNumberRecord = (inp: unknown): inp is NumberRecord => zNumberRecord.safeParse(inp).success

export const isNumbers = (inp: unknown): inp is Numbers => zNumbers.safeParse(inp).success

export const isNumberStringRecord = (inp: unknown): inp is NumberStringRecord =>
    zNumberStringRecord.safeParse(inp).success

export const isPasswordField = (inp: unknown): inp is PasswordField => zPasswordField.safeParse(inp).success

export const isPasswordFields = (inp: unknown): inp is PasswordFields => zPasswordFields.safeParse(inp).success

export const isPasswordInput = (inp: unknown): inp is PasswordInput => zPasswordInput.safeParse(inp).success

export const isPasswordInputs = (inp: unknown): inp is PasswordInputs => zPasswordInputs.safeParse(inp).success

export const isPaymentProvider = (inp: unknown): inp is PaymentProvider => zPaymentProvider.safeParse(inp).success

export const isPaymentProviders = (inp: unknown): inp is PaymentProviders => zPaymentProviders.safeParse(inp).success

export const isPayPal = (inp: unknown): inp is PayPal => zPayPal.safeParse(inp).success

export const isPayPals = (inp: unknown): inp is PayPals => zPayPals.safeParse(inp).success

export const isPositiveNumber = (inp: unknown): inp is PositiveNumber => zPositiveNumber.safeParse(inp).success

export const isPositiveNumbers = (inp: unknown): inp is PositiveNumbers => zPositiveNumbers.safeParse(inp).success

export const isSpreadString = (inp: unknown): inp is SpreadString => zSpreadString.safeParse(inp).success

export const isSpreadStrings = (inp: unknown): inp is SpreadStrings => zSpreadStrings.safeParse(inp).success

export const isString = (inp: unknown): inp is String => zString.safeParse(inp).success

export const isStringRecord = (inp: unknown): inp is StringRecord => zStringRecord.safeParse(inp).success

export const isStringRecords = (inp: unknown): inp is StringRecords => zStringRecords.safeParse(inp).success

export const isStrings = (inp: unknown): inp is Strings => zStrings.safeParse(inp).success

export const isStringStringRecord = (inp: unknown): inp is StringStringRecord =>
    zStringStringRecord.safeParse(inp).success

export const isStringStringRecords = (inp: unknown): inp is StringStringRecords =>
    zStringStringRecords.safeParse(inp).success

export const isStripe = (inp: unknown): inp is Stripe => zStripe.safeParse(inp).success

export const isStripePaymentState = (inp: unknown): inp is StripePaymentState =>
    zStripePaymentState.safeParse(inp).success

export const isStripePaymentStates = (inp: unknown): inp is StripePaymentStates =>
    zStripePaymentStates.safeParse(inp).success

export const isStripes = (inp: unknown): inp is Stripes => zStripes.safeParse(inp).success

export const isUnknown = (inp: unknown): inp is Unknown => zUnknown.safeParse(inp).success

export const isUrl = (inp: unknown): inp is Url => zUrl.safeParse(inp).success

export const isUrls = (inp: unknown): inp is Urls => zUrls.safeParse(inp).success

export const isUserActiveState = (inp: unknown): inp is UserActiveState => zUserActiveState.safeParse(inp).success

export const isUserActiveStateCode = (inp: unknown): inp is UserActiveStateCode =>
    zUserActiveStateCode.safeParse(inp).success

export const isUserActiveStateCodes = (inp: unknown): inp is UserActiveStateCodes =>
    zUserActiveStateCodes.safeParse(inp).success

export const isUserActiveStates = (inp: unknown): inp is UserActiveStates => zUserActiveStates.safeParse(inp).success

export const isUserActiveStateTitle = (inp: unknown): inp is UserActiveStateTitle =>
    zUserActiveStateTitle.safeParse(inp).success

export const isUserActiveStateTitles = (inp: unknown): inp is UserActiveStateTitles =>
    zUserActiveStateTitles.safeParse(inp).success

export const isUserActiveStateType = (inp: unknown): inp is UserActiveStateType =>
    zUserActiveStateType.safeParse(inp).success

export const isUserActiveStateTypes = (inp: unknown): inp is UserActiveStateTypes =>
    zUserActiveStateTypes.safeParse(inp).success

export const isUserActiveStatus = (inp: unknown): inp is UserActiveStatus => zUserActiveStatus.safeParse(inp).success

export const isUserActiveStatuses = (inp: unknown): inp is UserActiveStatuses =>
    zUserActiveStatuses.safeParse(inp).success

export const isUserBannedStateType = (inp: unknown): inp is UserBannedStateType =>
    zUserBannedStateType.safeParse(inp).success

export const isUserBannedStateTypes = (inp: unknown): inp is UserBannedStateTypes =>
    zUserBannedStateTypes.safeParse(inp).success

export const isUserInactiveStateType = (inp: unknown): inp is UserInactiveStateType =>
    zUserInactiveStateType.safeParse(inp).success

export const isUserInactiveStateTypes = (inp: unknown): inp is UserInactiveStateTypes =>
    zUserInactiveStateTypes.safeParse(inp).success

export const isUsername = (inp: unknown): inp is Username => zUsername.safeParse(inp).success

export const isUsernames = (inp: unknown): inp is Usernames => zUsernames.safeParse(inp).success

export const isUserPendingStateType = (inp: unknown): inp is UserPendingStateType =>
    zUserPendingStateType.safeParse(inp).success

export const isUserPendingStateTypes = (inp: unknown): inp is UserPendingStateTypes =>
    zUserPendingStateTypes.safeParse(inp).success

export const isUserPin = (inp: unknown): inp is UserPin => zUserPin.safeParse(inp).success

export const isUserPins = (inp: unknown): inp is UserPins => zUserPins.safeParse(inp).success

export const isUserStateCodeActive = (inp: unknown): inp is UserStateCodeActive =>
    zUserStateCodeActive.safeParse(inp).success

export const isUserStateCodeActives = (inp: unknown): inp is UserStateCodeActives =>
    zUserStateCodeActives.safeParse(inp).success

export const isUserStateCodeBanned = (inp: unknown): inp is UserStateCodeBanned =>
    zUserStateCodeBanned.safeParse(inp).success

export const isUserStateCodeBanneds = (inp: unknown): inp is UserStateCodeBanneds =>
    zUserStateCodeBanneds.safeParse(inp).success

export const isUserStateCodeInactive = (inp: unknown): inp is UserStateCodeInactive =>
    zUserStateCodeInactive.safeParse(inp).success

export const isUserStateCodeInactives = (inp: unknown): inp is UserStateCodeInactives =>
    zUserStateCodeInactives.safeParse(inp).success

export const isUserStateCodePending = (inp: unknown): inp is UserStateCodePending =>
    zUserStateCodePending.safeParse(inp).success

export const isUserStateCodePendings = (inp: unknown): inp is UserStateCodePendings =>
    zUserStateCodePendings.safeParse(inp).success

export const isUserStateTitleActive = (inp: unknown): inp is UserStateTitleActive =>
    zUserStateTitleActive.safeParse(inp).success

export const isUserStateTitleActives = (inp: unknown): inp is UserStateTitleActives =>
    zUserStateTitleActives.safeParse(inp).success

export const isUserStateTitleBanned = (inp: unknown): inp is UserStateTitleBanned =>
    zUserStateTitleBanned.safeParse(inp).success

export const isUserStateTitleBanneds = (inp: unknown): inp is UserStateTitleBanneds =>
    zUserStateTitleBanneds.safeParse(inp).success

export const isUserStateTitleInactive = (inp: unknown): inp is UserStateTitleInactive =>
    zUserStateTitleInactive.safeParse(inp).success

export const isUserStateTitleInactives = (inp: unknown): inp is UserStateTitleInactives =>
    zUserStateTitleInactives.safeParse(inp).success

export const isUserStateTitlePending = (inp: unknown): inp is UserStateTitlePending =>
    zUserStateTitlePending.safeParse(inp).success

export const isUserStateTitlePendings = (inp: unknown): inp is UserStateTitlePendings =>
    zUserStateTitlePendings.safeParse(inp).success
