// WARNING:
// This file is automatically generated.
// Do not edit manually.

import {
    zAccessLog,
    zAccessLogs,
    zAccessToken,
    zAccessTokens,
    zAnonPrincipal,
    zAnonPrincipals,
    zAppClient,
    zAppClients,
    zAuthCheckResult,
    zAuthCheckResults,
    zBasePrivilege,
    zBasePrivileges,
    zCommon,
    zCommons,
    zCurrentUser,
    zCurrentUsers,
    zDataRecord,
    zDataRecords,
    zDomain,
    zDomains,
    zEmail,
    zEmails,
    zEmailTemplate,
    zEmailTemplates,
    zEvent,
    zEvents,
    zGenuineCard,
    zGenuineCards,
    zGetUserGrantablePrivilegesResult,
    zIpn,
    zIpnRequest,
    zIpnRequests,
    zIpns,
    zIPrincipal,
    zIPrincipals,
    zKey,
    zKeys,
    zMembership,
    zMembershipBase,
    zMembershipPeriod,
    zMembershipPeriodDay,
    zMembershipPeriodDays,
    zMembershipPeriodMonth,
    zMembershipPeriodMonths,
    zMembershipPeriods,
    zMembershipPeriodYear,
    zMembershipPeriodYears,
    zMemberships,
    zMembershipWithId,
    zMembershipWithIds,
    zMetricServiceBaseRangeResult,
    zMetricServiceBaseRangeResults,
    zMetricServiceGetCreatedDatesResult,
    zMetricServiceGetCreatedDatesResults,
    zMetricServiceGetMembersResult,
    zMetricServiceGetMembersResults,
    zMetricServiceGetRevenueResult,
    zMetricServiceGetRevenueResults,
    zMetricServiceGroupType,
    zMetricServiceGroupTypes,
    zMetricServiceNewKeyholdersResult,
    zMetricServiceNewKeyholdersResults,
    zMetricServiceNewMembersResult,
    zMetricServiceNewMembersResults,
    zMetricServiceResult,
    zMetricServiceResults,
    zMetricServiceRevenueByMembership,
    zMetricServiceRevenueByMemberships,
    zMetricServiceRevenueResultSet,
    zMetricServiceRevenueResultSets,
    zMetricServiceTotalKeyHoldersResult,
    zMetricServiceTotalKeyHoldersResults,
    zMetricServiceTotalMembersResult,
    zMetricServiceTotalMembersResults,
    zMetricServiceValueResult,
    zMetricServiceValueResults,
    zPartialUser,
    zPartialUsers,
    zPayment,
    zPayments,
    zPrincipalUser,
    zPrincipalUsers,
    zPrivilege,
    zPrivileges,
    zPrivilegesField,
    zPrivilegesFields,
    zRefreshToken,
    zRefreshTokens,
    zRevenueByMembersType,
    zRevenueByMembersTypes,
    zStripeEvent,
    zStripeEvents,
    zSystemPreference,
    zSystemPreferences,
    zTrimmedAppClient,
    zTrimmedAppClientOwner,
    zTrimmedAppClientOwners,
    zTrimmedAppClients,
    zTrimmedUser,
    zTrimmedUsers,
    zUser,
    zUserPrincipal,
    zUsers,
    zWebHook,
    zWebHookBase,
    zWebHooks
} from '@/lib/validators/records.ts'

import type {
    AccessLog,
    AccessLogs,
    AccessToken,
    AccessTokens,
    AnonPrincipal,
    AnonPrincipals,
    AppClient,
    AppClients,
    AuthCheckResult,
    AuthCheckResults,
    BasePrivilege,
    BasePrivileges,
    Common,
    Commons,
    CurrentUser,
    CurrentUsers,
    DataRecord,
    DataRecords,
    Domain,
    Domains,
    Email,
    Emails,
    EmailTemplate,
    EmailTemplates,
    Event,
    Events,
    GenuineCard,
    GenuineCards,
    GetUserGrantablePrivilegesResult,
    Ipn,
    IpnRequest,
    IpnRequests,
    Ipns,
    IPrincipal,
    IPrincipals,
    Key,
    Keys,
    Membership,
    MembershipBase,
    MembershipPeriod,
    MembershipPeriodDay,
    MembershipPeriodDays,
    MembershipPeriodMonth,
    MembershipPeriodMonths,
    MembershipPeriods,
    MembershipPeriodYear,
    MembershipPeriodYears,
    Memberships,
    MembershipWithId,
    MembershipWithIds,
    MetricServiceBaseRangeResult,
    MetricServiceBaseRangeResults,
    MetricServiceGetCreatedDatesResult,
    MetricServiceGetCreatedDatesResults,
    MetricServiceGetMembersResult,
    MetricServiceGetMembersResults,
    MetricServiceGetRevenueResult,
    MetricServiceGetRevenueResults,
    MetricServiceGroupType,
    MetricServiceGroupTypes,
    MetricServiceNewKeyholdersResult,
    MetricServiceNewKeyholdersResults,
    MetricServiceNewMembersResult,
    MetricServiceNewMembersResults,
    MetricServiceResult,
    MetricServiceResults,
    MetricServiceRevenueByMembership,
    MetricServiceRevenueByMemberships,
    MetricServiceRevenueResultSet,
    MetricServiceRevenueResultSets,
    MetricServiceTotalKeyHoldersResult,
    MetricServiceTotalKeyHoldersResults,
    MetricServiceTotalMembersResult,
    MetricServiceTotalMembersResults,
    MetricServiceValueResult,
    MetricServiceValueResults,
    PartialUser,
    PartialUsers,
    Payment,
    Payments,
    PrincipalUser,
    PrincipalUsers,
    Privilege,
    Privileges,
    PrivilegesField,
    PrivilegesFields,
    RefreshToken,
    RefreshTokens,
    RevenueByMembersType,
    RevenueByMembersTypes,
    StripeEvent,
    StripeEvents,
    SystemPreference,
    SystemPreferences,
    TrimmedAppClient,
    TrimmedAppClientOwner,
    TrimmedAppClientOwners,
    TrimmedAppClients,
    TrimmedUser,
    TrimmedUsers,
    User,
    UserPrincipal,
    Users,
    WebHook,
    WebHookBase,
    WebHooks
} from '@/types/validators/records.ts'

export const isAccessLog = (inp: unknown): inp is AccessLog => zAccessLog.safeParse(inp).success

export const isAccessLogs = (inp: unknown): inp is AccessLogs => zAccessLogs.safeParse(inp).success

export const isAccessToken = (inp: unknown): inp is AccessToken => zAccessToken.safeParse(inp).success

export const isAccessTokens = (inp: unknown): inp is AccessTokens => zAccessTokens.safeParse(inp).success

export const isAnonPrincipal = (inp: unknown): inp is AnonPrincipal => zAnonPrincipal.safeParse(inp).success

export const isAnonPrincipals = (inp: unknown): inp is AnonPrincipals => zAnonPrincipals.safeParse(inp).success

export const isAppClient = (inp: unknown): inp is AppClient => zAppClient.safeParse(inp).success

export const isAppClients = (inp: unknown): inp is AppClients => zAppClients.safeParse(inp).success

export const isAuthCheckResult = (inp: unknown): inp is AuthCheckResult => zAuthCheckResult.safeParse(inp).success

export const isAuthCheckResults = (inp: unknown): inp is AuthCheckResults => zAuthCheckResults.safeParse(inp).success

export const isBasePrivilege = (inp: unknown): inp is BasePrivilege => zBasePrivilege.safeParse(inp).success

export const isBasePrivileges = (inp: unknown): inp is BasePrivileges => zBasePrivileges.safeParse(inp).success

export const isCommon = (inp: unknown): inp is Common => zCommon.safeParse(inp).success

export const isCommons = (inp: unknown): inp is Commons => zCommons.safeParse(inp).success

export const isCurrentUser = (inp: unknown): inp is CurrentUser => zCurrentUser.safeParse(inp).success

export const isCurrentUsers = (inp: unknown): inp is CurrentUsers => zCurrentUsers.safeParse(inp).success

export const isDataRecord = (inp: unknown): inp is DataRecord => zDataRecord.safeParse(inp).success

export const isDataRecords = (inp: unknown): inp is DataRecords => zDataRecords.safeParse(inp).success

export const isDomain = (inp: unknown): inp is Domain => zDomain.safeParse(inp).success

export const isDomains = (inp: unknown): inp is Domains => zDomains.safeParse(inp).success

export const isEmail = (inp: unknown): inp is Email => zEmail.safeParse(inp).success

export const isEmails = (inp: unknown): inp is Emails => zEmails.safeParse(inp).success

export const isEmailTemplate = (inp: unknown): inp is EmailTemplate => zEmailTemplate.safeParse(inp).success

export const isEmailTemplates = (inp: unknown): inp is EmailTemplates => zEmailTemplates.safeParse(inp).success

export const isEvent = (inp: unknown): inp is Event => zEvent.safeParse(inp).success

export const isEvents = (inp: unknown): inp is Events => zEvents.safeParse(inp).success

export const isGenuineCard = (inp: unknown): inp is GenuineCard => zGenuineCard.safeParse(inp).success

export const isGenuineCards = (inp: unknown): inp is GenuineCards => zGenuineCards.safeParse(inp).success

export const isGetUserGrantablePrivilegesResult = (inp: unknown): inp is GetUserGrantablePrivilegesResult =>
    zGetUserGrantablePrivilegesResult.safeParse(inp).success

export const isIpn = (inp: unknown): inp is Ipn => zIpn.safeParse(inp).success

export const isIpnRequest = (inp: unknown): inp is IpnRequest => zIpnRequest.safeParse(inp).success

export const isIpnRequests = (inp: unknown): inp is IpnRequests => zIpnRequests.safeParse(inp).success

export const isIpns = (inp: unknown): inp is Ipns => zIpns.safeParse(inp).success

export const isIPrincipal = (inp: unknown): inp is IPrincipal => zIPrincipal.safeParse(inp).success

export const isIPrincipals = (inp: unknown): inp is IPrincipals => zIPrincipals.safeParse(inp).success

export const isKey = (inp: unknown): inp is Key => zKey.safeParse(inp).success

export const isKeys = (inp: unknown): inp is Keys => zKeys.safeParse(inp).success

export const isMembership = (inp: unknown): inp is Membership => zMembership.safeParse(inp).success

export const isMembershipBase = (inp: unknown): inp is MembershipBase => zMembershipBase.safeParse(inp).success

export const isMembershipPeriod = (inp: unknown): inp is MembershipPeriod => zMembershipPeriod.safeParse(inp).success

export const isMembershipPeriodDay = (inp: unknown): inp is MembershipPeriodDay =>
    zMembershipPeriodDay.safeParse(inp).success

export const isMembershipPeriodDays = (inp: unknown): inp is MembershipPeriodDays =>
    zMembershipPeriodDays.safeParse(inp).success

export const isMembershipPeriodMonth = (inp: unknown): inp is MembershipPeriodMonth =>
    zMembershipPeriodMonth.safeParse(inp).success

export const isMembershipPeriodMonths = (inp: unknown): inp is MembershipPeriodMonths =>
    zMembershipPeriodMonths.safeParse(inp).success

export const isMembershipPeriods = (inp: unknown): inp is MembershipPeriods => zMembershipPeriods.safeParse(inp).success

export const isMembershipPeriodYear = (inp: unknown): inp is MembershipPeriodYear =>
    zMembershipPeriodYear.safeParse(inp).success

export const isMembershipPeriodYears = (inp: unknown): inp is MembershipPeriodYears =>
    zMembershipPeriodYears.safeParse(inp).success

export const isMemberships = (inp: unknown): inp is Memberships => zMemberships.safeParse(inp).success

export const isMembershipWithId = (inp: unknown): inp is MembershipWithId => zMembershipWithId.safeParse(inp).success

export const isMembershipWithIds = (inp: unknown): inp is MembershipWithIds => zMembershipWithIds.safeParse(inp).success

export const isMetricServiceBaseRangeResult = (inp: unknown): inp is MetricServiceBaseRangeResult =>
    zMetricServiceBaseRangeResult.safeParse(inp).success

export const isMetricServiceBaseRangeResults = (inp: unknown): inp is MetricServiceBaseRangeResults =>
    zMetricServiceBaseRangeResults.safeParse(inp).success

export const isMetricServiceGetCreatedDatesResult = (inp: unknown): inp is MetricServiceGetCreatedDatesResult =>
    zMetricServiceGetCreatedDatesResult.safeParse(inp).success

export const isMetricServiceGetCreatedDatesResults = (inp: unknown): inp is MetricServiceGetCreatedDatesResults =>
    zMetricServiceGetCreatedDatesResults.safeParse(inp).success

export const isMetricServiceGetMembersResult = (inp: unknown): inp is MetricServiceGetMembersResult =>
    zMetricServiceGetMembersResult.safeParse(inp).success

export const isMetricServiceGetMembersResults = (inp: unknown): inp is MetricServiceGetMembersResults =>
    zMetricServiceGetMembersResults.safeParse(inp).success

export const isMetricServiceGetRevenueResult = (inp: unknown): inp is MetricServiceGetRevenueResult =>
    zMetricServiceGetRevenueResult.safeParse(inp).success

export const isMetricServiceGetRevenueResults = (inp: unknown): inp is MetricServiceGetRevenueResults =>
    zMetricServiceGetRevenueResults.safeParse(inp).success

export const isMetricServiceGroupType = (inp: unknown): inp is MetricServiceGroupType =>
    zMetricServiceGroupType.safeParse(inp).success

export const isMetricServiceGroupTypes = (inp: unknown): inp is MetricServiceGroupTypes =>
    zMetricServiceGroupTypes.safeParse(inp).success

export const isMetricServiceNewKeyholdersResult = (inp: unknown): inp is MetricServiceNewKeyholdersResult =>
    zMetricServiceNewKeyholdersResult.safeParse(inp).success

export const isMetricServiceNewKeyholdersResults = (inp: unknown): inp is MetricServiceNewKeyholdersResults =>
    zMetricServiceNewKeyholdersResults.safeParse(inp).success

export const isMetricServiceNewMembersResult = (inp: unknown): inp is MetricServiceNewMembersResult =>
    zMetricServiceNewMembersResult.safeParse(inp).success

export const isMetricServiceNewMembersResults = (inp: unknown): inp is MetricServiceNewMembersResults =>
    zMetricServiceNewMembersResults.safeParse(inp).success

export const isMetricServiceResult = (inp: unknown): inp is MetricServiceResult =>
    zMetricServiceResult.safeParse(inp).success

export const isMetricServiceResults = (inp: unknown): inp is MetricServiceResults =>
    zMetricServiceResults.safeParse(inp).success

export const isMetricServiceRevenueByMembership = (inp: unknown): inp is MetricServiceRevenueByMembership =>
    zMetricServiceRevenueByMembership.safeParse(inp).success

export const isMetricServiceRevenueByMemberships = (inp: unknown): inp is MetricServiceRevenueByMemberships =>
    zMetricServiceRevenueByMemberships.safeParse(inp).success

export const isMetricServiceRevenueResultSet = (inp: unknown): inp is MetricServiceRevenueResultSet =>
    zMetricServiceRevenueResultSet.safeParse(inp).success

export const isMetricServiceRevenueResultSets = (inp: unknown): inp is MetricServiceRevenueResultSets =>
    zMetricServiceRevenueResultSets.safeParse(inp).success

export const isMetricServiceTotalKeyHoldersResult = (inp: unknown): inp is MetricServiceTotalKeyHoldersResult =>
    zMetricServiceTotalKeyHoldersResult.safeParse(inp).success

export const isMetricServiceTotalKeyHoldersResults = (inp: unknown): inp is MetricServiceTotalKeyHoldersResults =>
    zMetricServiceTotalKeyHoldersResults.safeParse(inp).success

export const isMetricServiceTotalMembersResult = (inp: unknown): inp is MetricServiceTotalMembersResult =>
    zMetricServiceTotalMembersResult.safeParse(inp).success

export const isMetricServiceTotalMembersResults = (inp: unknown): inp is MetricServiceTotalMembersResults =>
    zMetricServiceTotalMembersResults.safeParse(inp).success

export const isMetricServiceValueResult = (inp: unknown): inp is MetricServiceValueResult =>
    zMetricServiceValueResult.safeParse(inp).success

export const isMetricServiceValueResults = (inp: unknown): inp is MetricServiceValueResults =>
    zMetricServiceValueResults.safeParse(inp).success

export const isPartialUser = (inp: unknown): inp is PartialUser => zPartialUser.safeParse(inp).success

export const isPartialUsers = (inp: unknown): inp is PartialUsers => zPartialUsers.safeParse(inp).success

export const isPayment = (inp: unknown): inp is Payment => zPayment.safeParse(inp).success

export const isPayments = (inp: unknown): inp is Payments => zPayments.safeParse(inp).success

export const isPrincipalUser = (inp: unknown): inp is PrincipalUser => zPrincipalUser.safeParse(inp).success

export const isPrincipalUsers = (inp: unknown): inp is PrincipalUsers => zPrincipalUsers.safeParse(inp).success

export const isPrivilege = (inp: unknown): inp is Privilege => zPrivilege.safeParse(inp).success

export const isPrivileges = (inp: unknown): inp is Privileges => zPrivileges.safeParse(inp).success

export const isPrivilegesField = (inp: unknown): inp is PrivilegesField => zPrivilegesField.safeParse(inp).success

export const isPrivilegesFields = (inp: unknown): inp is PrivilegesFields => zPrivilegesFields.safeParse(inp).success

export const isRefreshToken = (inp: unknown): inp is RefreshToken => zRefreshToken.safeParse(inp).success

export const isRefreshTokens = (inp: unknown): inp is RefreshTokens => zRefreshTokens.safeParse(inp).success

export const isRevenueByMembersType = (inp: unknown): inp is RevenueByMembersType =>
    zRevenueByMembersType.safeParse(inp).success

export const isRevenueByMembersTypes = (inp: unknown): inp is RevenueByMembersTypes =>
    zRevenueByMembersTypes.safeParse(inp).success

export const isStripeEvent = (inp: unknown): inp is StripeEvent => zStripeEvent.safeParse(inp).success

export const isStripeEvents = (inp: unknown): inp is StripeEvents => zStripeEvents.safeParse(inp).success

export const isSystemPreference = (inp: unknown): inp is SystemPreference => zSystemPreference.safeParse(inp).success

export const isSystemPreferences = (inp: unknown): inp is SystemPreferences => zSystemPreferences.safeParse(inp).success

export const isTrimmedAppClient = (inp: unknown): inp is TrimmedAppClient => zTrimmedAppClient.safeParse(inp).success

export const isTrimmedAppClientOwner = (inp: unknown): inp is TrimmedAppClientOwner =>
    zTrimmedAppClientOwner.safeParse(inp).success

export const isTrimmedAppClientOwners = (inp: unknown): inp is TrimmedAppClientOwners =>
    zTrimmedAppClientOwners.safeParse(inp).success

export const isTrimmedAppClients = (inp: unknown): inp is TrimmedAppClients => zTrimmedAppClients.safeParse(inp).success

export const isTrimmedUser = (inp: unknown): inp is TrimmedUser => zTrimmedUser.safeParse(inp).success

export const isTrimmedUsers = (inp: unknown): inp is TrimmedUsers => zTrimmedUsers.safeParse(inp).success

export const isUser = (inp: unknown): inp is User => zUser.safeParse(inp).success

export const isUserPrincipal = (inp: unknown): inp is UserPrincipal => zUserPrincipal.safeParse(inp).success

export const isUsers = (inp: unknown): inp is Users => zUsers.safeParse(inp).success

export const isWebHook = (inp: unknown): inp is WebHook => zWebHook.safeParse(inp).success

export const isWebHookBase = (inp: unknown): inp is WebHookBase => zWebHookBase.safeParse(inp).success

export const isWebHooks = (inp: unknown): inp is WebHooks => zWebHooks.safeParse(inp).success
