version: "3.5"

services:        
  gateway:
    image: vanhack/nomos.gateway:${NOMOS_VERSION:-latest}
    environment:
      - VIRTUAL_HOST=${NOMOS_VIRTUAL_HOST}
    networks:
      proxy:
        aliases:
          - nomos_gateway
    depends_on:
      - visualizer
    deploy:
      placement:
        constraints: [node.role == manager]

  adminvpn:
    image: vanhack/nomos.adminvpn:${NOMOS_VERSION:-latest}
    secrets:
      - adminvpn_password
    ports:
      - "2222:22"
    networks:
      - admin
    deploy:
      placement:
        constraints: [node.role == manager]
  
  core:
    image: vanhack/nomos.core:${NOMOS_VERSION:-latest}
    secrets:
      - mq_vhost
      - mq_user
      - mq_password
      - db_user
      - db_password
      - db_database
      - ses_region
      - ses_clientid
      - ses_secret
      - from_email
      - oauth_github_client
      - oauth_github_secret
      - oauth_slack_client
      - oauth_slack_secret
      - oauth_slack_team
      - oauth_google_client
      - oauth_google_secret
    networks:
      data:
      app:
      proxy:
        aliases:
          - core
    depends_on:
      - rabbitmq
      - manager
    deploy:
      mode: replicated
      
  web:
    image: vanhack/nomos.web:${NOMOS_VERSION:-latest}
    networks:
      proxy:
        aliases:
          - web
    deploy:
      mode: replicated
      
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      proxy:
        aliases:
          - nomos_visualizer
      admin:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
          
  rabbitmq:
    image: rabbitmq:3-management
    secrets:
      - mq_vhost
      - mq_user
      - mq_password
    environment:
      - RABBITMQ_DEFAULT_VHOST_FILE=/run/secrets/mq_vhost
      - RABBITMQ_DEFAULT_USER_FILE=/run/secrets/mq_user
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/mq_password
    networks:
      - app
      - admin
    deploy:
      mode: replicated
      replicas: 1
          
  manager:
    image: vanhack/nomos.database.manager:${NOMOS_VERSION:-latest}
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_database
    networks:
      - data
      - admin
    depends_on:
      - master
      - replica
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
          
  master:
    image: vanhack/nomos.database.master:${NOMOS_VERSION:-latest}
    secrets:
      - db_root_password
      - db_user
      - db_password
      - db_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_database
    volumes:
      - "/srv/nomos/storage/master:/var/lib/mysql"
    networks:
      - data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.nomos.persistence.master == storage]
      
  replica:
    image: vanhack/nomos.database.replica:${NOMOS_VERSION:-latest}
    secrets:
      - db_root_password
      - db_database
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE_FILE=/run/secrets/db_database
    volumes:
      - "/srv/nomos/storage/replica:/var/lib/mysql"
    networks:
      - data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.nomos.persistence.replica == storage]
      
  webhooker:
    image: vanhack/nomos.webhooker:${NOMOS_VERSION:-latest}
    secrets:
      - mq_user
      - mq_password
      - mq_vhost
      - webhooker_token
    environment:
      - NOMOS_CORE_REJECTUNAUTHORIZED=${NOMOS_CORE_REJECTUNAUTHORIZED:-true}
    networks:
      - app
      - proxy
      - admin
    depends_on:
      - rabbitmq
      - core
    deploy:
      mode: replicated
      replicas: 1
      
secrets:
  mq_vhost:
    file: ./secrets/mq_vhost
    name: mq_vhost_${NOMOS_SECRETS_VERSION}
  mq_user:
    file: ./secrets/mq_user
    name: mq_user_${NOMOS_SECRETS_VERSION}
  mq_password:
    file: ./secrets/mq_password
    name: mq_password_${NOMOS_SECRETS_VERSION}
  db_root_password:
    file: ./secrets/db_root_password
    name: db_root_password_${NOMOS_SECRETS_VERSION}
  db_user:
    file: ./secrets/db_user
    name: db_user_${NOMOS_SECRETS_VERSION}
  db_password:
    file: ./secrets/db_password
    name: db_password_${NOMOS_SECRETS_VERSION}
  db_database:
    file: ./secrets/db_database
    name: db_database_${NOMOS_SECRETS_VERSION}
  ses_region:
    file: ./secrets/ses_region
    name: ses_region_${NOMOS_SECRETS_VERSION}
  ses_clientid:
    file: ./secrets/ses_clientid
    name: ses_clientid_${NOMOS_SECRETS_VERSION}
  ses_secret:
    file: ./secrets/ses_secret
    name: ses_secret_${NOMOS_SECRETS_VERSION}
  from_email:
    file: ./secrets/from_email
    name: from_email_${NOMOS_SECRETS_VERSION}
  oauth_github_client:
    file: ./secrets/oauth_github_client
    name: oauth_github_client_${NOMOS_SECRETS_VERSION}
  oauth_github_secret:
    file: ./secrets/oauth_github_secret
    name: oauth_github_secret_${NOMOS_SECRETS_VERSION}
  oauth_slack_client:
    file: ./secrets/oauth_slack_client
    name: oauth_slack_client_${NOMOS_SECRETS_VERSION}
  oauth_slack_secret:
    file: ./secrets/oauth_slack_secret
    name: oauth_slack_secret_${NOMOS_SECRETS_VERSION}
  oauth_slack_team:
    file: ./secrets/oauth_slack_team
    name: oauth_slack_team_${NOMOS_SECRETS_VERSION}
  oauth_google_client:
    file: ./secrets/oauth_google_client
    name: oauth_google_client_${NOMOS_SECRETS_VERSION}
  oauth_google_secret:
    file: ./secrets/oauth_google_secret
    name: oauth_google_secret_${NOMOS_SECRETS_VERSION}
  adminvpn_password:
    file: ./secrets/adminvpn_password
    name: adminvpn_password_${NOMOS_SECRETS_VERSION}
  webhooker_token:
    file: ./secrets/webhooker_token
    name: webhooker_token_${NOMOS_SECRETS_VERSION}

networks:
  data:
  app:
  proxy:
    external: true
  admin:
    external: true
