<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class AccessLog {
    public bool $authorized;

    public string $from_ip;
    public int $id;

    public string $key;

    public string $time;

    public string $type;

    public int $userid;

    public function __construct(\app\domain\AccessLog $accessLog) {
        $this->id = $accessLog->id;
        $this->key = $accessLog->key;
        $this->type = $accessLog->type;
        $this->authorized = $accessLog->authorized;
        $this->from_ip = $accessLog->from_ip;
        $this->time = $accessLog->time;
        $this->userid = $accessLog->userid;
    }
}
