<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class AccessToken {
    public int $appclientid;

    public string $expires;
    public int $id;

    public string $token;

    public int $userid;

    public function __construct(\app\domain\AccessToken $accessToken) {
        $this->id = $accessToken->id;
        $this->token = $accessToken->token;
        $this->expires = $accessToken->expires;
        $this->userid = $accessToken->userid;
        $this->appclientid = $accessToken->appclientid;
    }
}
