<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class EmailTemplate {
    public string $body;

    public string $code;

    public string $help;

    public string $html;
    public int $id;

    public string $name;

    public string $subject;

    public function __construct(\app\domain\EmailTemplate $emailTemplate) {
        $this->id = $emailTemplate->id;
        $this->name = $emailTemplate->name;
        $this->code = $emailTemplate->code;
        $this->subject = $emailTemplate->subject;
        $this->help = $emailTemplate->help;
        $this->body = $emailTemplate->body;
        $this->html = $emailTemplate->html;
    }
}
