<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class GenuineCard {
    public bool $active;

    public string $created;
    public int $id;

    public string $issued;

    public string $key;

    public string $notes;

    public string $owneremail;

    public int $paymentid;

    public int $userid;

    public function __construct(\app\domain\GenuineCard $genuineCard) {
        $this->id = $genuineCard->id;
        $this->key = $genuineCard->key;
        $this->created = $genuineCard->created;
        $this->issued = $genuineCard->issued;
        $this->active = $genuineCard->active;
        $this->paymentid = $genuineCard->paymentid;
        $this->userid = $genuineCard->userid;
        $this->owneremail = $genuineCard->owneremail;
        $this->notes = $genuineCard->notes;
    }
}
