<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
enum IpnValidationEnum: int {
    case INVALID = 0;
    case VERIFIED = 1;
}
