<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class Membership {
    public bool $active;

    public string $code;

    public int $days;

    public string $description;
    public int $id;

    public string $period;

    public float $price;

    public bool $private;

    public bool $recurring;

    public string $title;

    public bool $trial;

    public function __construct(\app\domain\Membership $membership) {
        $this->id = $membership->id;
        $this->title = $membership->title;
        $this->code = $membership->code;
        $this->description = $membership->description;
        $this->price = $membership->price;
        $this->days = $membership->days;
        $this->period = $membership->period;
        $this->trial = $membership->trial;
        $this->recurring = $membership->recurring;
        $this->private = $membership->private;
        $this->active = $membership->active;
    }
}
