<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class PasswordResetRequest {
    public string $created;
    public int $id;

    public string $token;

    public int $userid;

    public function __construct(\app\domain\PasswordResetRequest $passwordResetRequest) {
        $this->id = $passwordResetRequest->id;
        $this->userid = $passwordResetRequest->userid;
        $this->token = $passwordResetRequest->token;
        $this->created = $passwordResetRequest->created;
    }
}
