<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
enum PaymentPpEnum {
    case MoneyBookers;
    case PayPal;
    case Stripe;
}
