<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class Privilege {
    public string $code;

    public string $description;

    public bool $enabled;

    public string $icon;
    public int $id;

    public string $name;

    public function __construct(\app\domain\Privilege $privilege) {
        $this->id = $privilege->id;
        $this->name = $privilege->name;
        $this->code = $privilege->code;
        $this->description = $privilege->description;
        $this->icon = $privilege->icon;
        $this->enabled = $privilege->enabled;
    }
}
