<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class SystemPreference {
    public bool $enabled;
    public int $id;

    public string $key;

    public string $notes;

    public string $value;

    public function __construct(\app\domain\SystemPreference $systemPreference) {
        $this->id = $systemPreference->id;
        $this->key = $systemPreference->key;
        $this->value = $systemPreference->value;
        $this->enabled = $systemPreference->enabled;
        $this->notes = $systemPreference->notes;
    }
}
