<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class User {
    public string $active;

    public string $avatar;

    public bool $cash;

    public string $cookie_id;

    public string $created;

    public string $email;

    public string $fname;
    public int $id;

    public string $lastip;

    public string $lastlogin;

    public string $lname;

    public string $mem_expire;

    public int $membership_id;

    public bool $newsletter;

    public string $notes;

    public string $password;

    public string $payment_email;

    public string $paypal_id;

    public string $stripe_email;

    public string $stripe_id;

    public string $token;

    public bool $trial_used;

    public int $userlevel;

    public string $username;

    public function __construct(\app\domain\User $user) {
        $this->id = $user->id;
        $this->username = $user->username;
        $this->password = $user->password;
        $this->membership_id = $user->membership_id;
        $this->mem_expire = $user->mem_expire;
        $this->trial_used = $user->trial_used;
        $this->email = $user->email;
        $this->fname = $user->fname;
        $this->lname = $user->lname;
        $this->token = $user->token;
        $this->cookie_id = $user->cookie_id;
        $this->newsletter = $user->newsletter;
        $this->cash = $user->cash;
        $this->userlevel = $user->userlevel;
        $this->notes = $user->notes;
        $this->created = $user->created;
        $this->lastlogin = $user->lastlogin;
        $this->lastip = $user->lastip;
        $this->avatar = $user->avatar;
        $this->active = $user->active;
        $this->paypal_id = $user->paypal_id;
        $this->payment_email = $user->payment_email;
        $this->stripe_id = $user->stripe_id;
        $this->stripe_email = $user->stripe_email;
    }
}
