<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class WebHook {
    public string $description;

    public bool $enabled;

    public int $eventid;

    public string $headers;
    public int $id;

    public string $method;

    public string $name;

    public string $translation;

    public string $url;

    public int $userid;

    public function __construct(\app\domain\WebHook $webHook) {
        $this->id = $webHook->id;
        $this->name = $webHook->name;
        $this->description = $webHook->description;
        $this->enabled = $webHook->enabled;
        $this->userid = $webHook->userid;
        $this->url = $webHook->url;
        $this->translation = $webHook->translation;
        $this->headers = $webHook->headers;
        $this->method = $webHook->method;
        $this->eventid = $webHook->eventid;
    }
}
