services:
  proxy:
    depends_on:
      frontend-web:
        condition: service_started
      frontend-react:
        condition: service_started
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ${PWD}/conf/nginx.conf:/etc/nginx/conf.d/default.conf
