// WARNING:
// This file is automatically generated.
// Do not edit manually.

import type { z } from 'zod'

import type {
    zAccessLog,
    zAccessLogs,
    zAccessToken,
    zAccessTokens,
    zAnonPrincipal,
    zAnonPrincipals,
    zAppClient,
    zAppClients,
    zAuthCheckResult,
    zAuthCheckResults,
    zBasePrivilege,
    zBasePrivileges,
    zCommon,
    zCommons,
    zCurrentUser,
    zCurrentUsers,
    zDataRecord,
    zDataRecords,
    zDomain,
    zDomains,
    zEmail,
    zEmailTemplate,
    zEmailTemplates,
    zEmails,
    zEvent,
    zEvents,
    zGenuineCard,
    zGenuineCards,
    zIPrincipal,
    zIPrincipals,
    zIpn,
    zIpnRequest,
    zIpnRequests,
    zIpns,
    zKey,
    zKeys,
    zMembership,
    zMembershipBase,
    zMembershipPeriod,
    zMembershipPeriodDay,
    zMembershipPeriodDays,
    zMembershipPeriodMonth,
    zMembershipPeriodMonths,
    zMembershipPeriodYear,
    zMembershipPeriodYears,
    zMembershipPeriods,
    zMembershipWithId,
    zMembershipWithIds,
    zMemberships,
    zMetricServiceBaseRangeResult,
    zMetricServiceBaseRangeResults,
    zMetricServiceGetCreatedDatesResult,
    zMetricServiceGetCreatedDatesResults,
    zMetricServiceGetMembersResult,
    zMetricServiceGetMembersResults,
    zMetricServiceGetRevenueResult,
    zMetricServiceGetRevenueResults,
    zMetricServiceGroupType,
    zMetricServiceGroupTypes,
    zMetricServiceNewKeyholdersResult,
    zMetricServiceNewKeyholdersResults,
    zMetricServiceNewMembersResult,
    zMetricServiceNewMembersResults,
    zMetricServiceResult,
    zMetricServiceResults,
    zMetricServiceRevenueByMembership,
    zMetricServiceRevenueByMemberships,
    zMetricServiceRevenueResultSet,
    zMetricServiceRevenueResultSets,
    zMetricServiceTotalKeyHoldersResult,
    zMetricServiceTotalKeyHoldersResults,
    zMetricServiceTotalMembersResult,
    zMetricServiceTotalMembersResults,
    zMetricServiceValueResult,
    zMetricServiceValueResults,
    zPartialUser,
    zPartialUsers,
    zPayment,
    zPayments,
    zPrincipalUser,
    zPrincipalUsers,
    zPrivilege,
    zPrivileges,
    zPrivilegesField,
    zPrivilegesFields,
    zRefreshToken,
    zRefreshTokens,
    zRevenueByMembersType,
    zRevenueByMembersTypes,
    zStripeEvent,
    zStripeEvents,
    zSystemPreference,
    zSystemPreferences,
    zTrimmedAppClient,
    zTrimmedAppClientOwner,
    zTrimmedAppClientOwners,
    zTrimmedAppClients,
    zTrimmedUser,
    zTrimmedUsers,
    zUser,
    zUserPrincipal,
    zUsers,
    zWebHook,
    zWebHookBase,
    zWebHooks
} from '@/lib/validators/records.ts'

export type AccessLog = z.infer<typeof zAccessLog>

export type AccessLogs = z.infer<typeof zAccessLogs>

export type AccessToken = z.infer<typeof zAccessToken>

export type AccessTokens = z.infer<typeof zAccessTokens>

export type AnonPrincipal = z.infer<typeof zAnonPrincipal>

export type AnonPrincipals = z.infer<typeof zAnonPrincipals>

export type AppClient = z.infer<typeof zAppClient>

export type AppClients = z.infer<typeof zAppClients>

export type AuthCheckResult = z.infer<typeof zAuthCheckResult>

export type AuthCheckResults = z.infer<typeof zAuthCheckResults>

export type BasePrivilege = z.infer<typeof zBasePrivilege>

export type BasePrivileges = z.infer<typeof zBasePrivileges>

export type Common = z.infer<typeof zCommon>

export type Commons = z.infer<typeof zCommons>

export type CurrentUser = z.infer<typeof zCurrentUser>

export type CurrentUsers = z.infer<typeof zCurrentUsers>

export type DataRecord = z.infer<typeof zDataRecord>

export type DataRecords = z.infer<typeof zDataRecords>

export type Domain = z.infer<typeof zDomain>

export type Domains = z.infer<typeof zDomains>

export type Email = z.infer<typeof zEmail>

export type EmailTemplate = z.infer<typeof zEmailTemplate>

export type EmailTemplates = z.infer<typeof zEmailTemplates>

export type Emails = z.infer<typeof zEmails>

export type Event = z.infer<typeof zEvent>

export type Events = z.infer<typeof zEvents>

export type GenuineCard = z.infer<typeof zGenuineCard>

export type GenuineCards = z.infer<typeof zGenuineCards>

export type IPrincipal = z.infer<typeof zIPrincipal>

export type IPrincipals = z.infer<typeof zIPrincipals>

export type Ipn = z.infer<typeof zIpn>

export type IpnRequest = z.infer<typeof zIpnRequest>

export type IpnRequests = z.infer<typeof zIpnRequests>

export type Ipns = z.infer<typeof zIpns>

export type Key = z.infer<typeof zKey>

export type Keys = z.infer<typeof zKeys>

export type Membership = z.infer<typeof zMembership>

export type MembershipBase = z.infer<typeof zMembershipBase>

export type MembershipPeriod = z.infer<typeof zMembershipPeriod>

export type MembershipPeriodDay = z.infer<typeof zMembershipPeriodDay>

export type MembershipPeriodDays = z.infer<typeof zMembershipPeriodDays>

export type MembershipPeriodMonth = z.infer<typeof zMembershipPeriodMonth>

export type MembershipPeriodMonths = z.infer<typeof zMembershipPeriodMonths>

export type MembershipPeriodYear = z.infer<typeof zMembershipPeriodYear>

export type MembershipPeriodYears = z.infer<typeof zMembershipPeriodYears>

export type MembershipPeriods = z.infer<typeof zMembershipPeriods>

export type MembershipWithId = z.infer<typeof zMembershipWithId>

export type MembershipWithIds = z.infer<typeof zMembershipWithIds>

export type Memberships = z.infer<typeof zMemberships>

export type MetricServiceBaseRangeResult = z.infer<typeof zMetricServiceBaseRangeResult>

export type MetricServiceBaseRangeResults = z.infer<typeof zMetricServiceBaseRangeResults>

export type MetricServiceGetCreatedDatesResult = z.infer<typeof zMetricServiceGetCreatedDatesResult>

export type MetricServiceGetCreatedDatesResults = z.infer<typeof zMetricServiceGetCreatedDatesResults>

export type MetricServiceGetMembersResult = z.infer<typeof zMetricServiceGetMembersResult>

export type MetricServiceGetMembersResults = z.infer<typeof zMetricServiceGetMembersResults>

export type MetricServiceGetRevenueResult = z.infer<typeof zMetricServiceGetRevenueResult>

export type MetricServiceGetRevenueResults = z.infer<typeof zMetricServiceGetRevenueResults>

export type MetricServiceGroupType = z.infer<typeof zMetricServiceGroupType>

export type MetricServiceGroupTypes = z.infer<typeof zMetricServiceGroupTypes>

export type MetricServiceNewKeyholdersResult = z.infer<typeof zMetricServiceNewKeyholdersResult>

export type MetricServiceNewKeyholdersResults = z.infer<typeof zMetricServiceNewKeyholdersResults>

export type MetricServiceNewMembersResult = z.infer<typeof zMetricServiceNewMembersResult>

export type MetricServiceNewMembersResults = z.infer<typeof zMetricServiceNewMembersResults>

export type MetricServiceResult = z.infer<typeof zMetricServiceResult>

export type MetricServiceResults = z.infer<typeof zMetricServiceResults>

export type MetricServiceRevenueByMembership = z.infer<typeof zMetricServiceRevenueByMembership>

export type MetricServiceRevenueByMemberships = z.infer<typeof zMetricServiceRevenueByMemberships>

export type MetricServiceRevenueResultSet = z.infer<typeof zMetricServiceRevenueResultSet>

export type MetricServiceRevenueResultSets = z.infer<typeof zMetricServiceRevenueResultSets>

export type MetricServiceTotalKeyHoldersResult = z.infer<typeof zMetricServiceTotalKeyHoldersResult>

export type MetricServiceTotalKeyHoldersResults = z.infer<typeof zMetricServiceTotalKeyHoldersResults>

export type MetricServiceTotalMembersResult = z.infer<typeof zMetricServiceTotalMembersResult>

export type MetricServiceTotalMembersResults = z.infer<typeof zMetricServiceTotalMembersResults>

export type MetricServiceValueResult = z.infer<typeof zMetricServiceValueResult>

export type MetricServiceValueResults = z.infer<typeof zMetricServiceValueResults>

export type PartialUser = z.infer<typeof zPartialUser>

export type PartialUsers = z.infer<typeof zPartialUsers>

export type Payment = z.infer<typeof zPayment>

export type Payments = z.infer<typeof zPayments>

export type PrincipalUser = z.infer<typeof zPrincipalUser>

export type PrincipalUsers = z.infer<typeof zPrincipalUsers>

export type Privilege = z.infer<typeof zPrivilege>

export type Privileges = z.infer<typeof zPrivileges>

export type PrivilegesField = z.infer<typeof zPrivilegesField>

export type PrivilegesFields = z.infer<typeof zPrivilegesFields>

export type RefreshToken = z.infer<typeof zRefreshToken>

export type RefreshTokens = z.infer<typeof zRefreshTokens>

export type RevenueByMembersType = z.infer<typeof zRevenueByMembersType>

export type RevenueByMembersTypes = z.infer<typeof zRevenueByMembersTypes>

export type StripeEvent = z.infer<typeof zStripeEvent>

export type StripeEvents = z.infer<typeof zStripeEvents>

export type SystemPreference = z.infer<typeof zSystemPreference>

export type SystemPreferences = z.infer<typeof zSystemPreferences>

export type TrimmedAppClient = z.infer<typeof zTrimmedAppClient>

export type TrimmedAppClientOwner = z.infer<typeof zTrimmedAppClientOwner>

export type TrimmedAppClientOwners = z.infer<typeof zTrimmedAppClientOwners>

export type TrimmedAppClients = z.infer<typeof zTrimmedAppClients>

export type TrimmedUser = z.infer<typeof zTrimmedUser>

export type TrimmedUsers = z.infer<typeof zTrimmedUsers>

export type User = z.infer<typeof zUser>

export type UserPrincipal = z.infer<typeof zUserPrincipal>

export type Users = z.infer<typeof zUsers>

export type WebHook = z.infer<typeof zWebHook>

export type WebHookBase = z.infer<typeof zWebHookBase>

export type WebHooks = z.infer<typeof zWebHooks>
