services:
    # backend needs the db started first
    backend-php:
        depends_on:
            mysql:
                condition: service_healthy
    mysql:
        image: mariadb:11.4
        environment:
            - MARIADB_USER=${NOMOS_DB_USER}
            - MARIADB_PASSWORD=${NOMOS_DB_PASSWORD}
            - MARIADB_DATABASE=${NOMOS_DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${PWD}/data/mysql:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            interval: 10s
            timeout: 5s
            retries: 3
