services:
    nomos-frontend:
        networks:
            - proxy

    nomos-backend:
        networks:
            - proxy

    nomos-webhooker:
        networks:
            - proxy

networks:
    proxy:
