FROM node:lts AS build

WORKDIR /build

COPY webhooker/ ./

RUN chmod 755 webhooker.sbin webhooker.console \
    && mv config.docker.js config.js \
    && npm ci

FROM node:lts

RUN mkdir -p /app/logs /app/webhooker

COPY --from=build /build /app/webhooker

WORKDIR /app/webhooker

CMD ["/app/webhooker/webhooker.sbin"]
