services:
    nomos-rabbitmq:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    nomos-webhooker:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    nomos-backend:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
    nomos-frontend:
        labels:
            - 'com.centurylinklabs.watchtower.enable=false'
