services:
    nomos-webhooker:
        external_links:
            - rabbitmq:nomos-rabbitmq
        networks:
            - rabbitmq

    nomos-backend:
        external_links:
            - rabbitmq:nomos-rabbitmq
        networks:
            - rabbitmq

networks:
    rabbitmq:
        external: true
