services:
    nomos-webhooker:
        image: vanhack/nomos-webhooker
        container_name: nomos-webhooker
        restart: always

    nomos-backend:
        depends_on:
            - nomos-webhooker
