<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class AppClient {
    public string $description;

    public bool $enabled;

    public string $expires;
    public int $id;

    public string $name;

    public string $redirecturi;

    public string $secret;

    public string $url;

    public int $userid;

    public function __construct(\app\domain\AppClient $appClient) {
        $this->id = $appClient->id;
        $this->secret = $appClient->secret;
        $this->expires = $appClient->expires;
        $this->userid = $appClient->userid;
        $this->name = $appClient->name;
        $this->description = $appClient->description;
        $this->url = $appClient->url;
        $this->redirecturi = $appClient->redirecturi;
        $this->enabled = $appClient->enabled;
    }
}
