<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class Event {
    public string $description;

    public string $domain;

    public bool $enabled;

    public string $event;
    public int $id;

    public string $name;

    public function __construct(\app\domain\Event $event) {
        $this->id = $event->id;
        $this->name = $event->name;
        $this->domain = $event->domain;
        $this->event = $event->event;
        $this->description = $event->description;
        $this->enabled = $event->enabled;
    }
}
