<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class Ipn {
    public string $created;
    public int $id;

    public string $item_name;

    public string $item_number;

    public string $payer_email;

    public string $payment_amount;

    public string $payment_currency;

    public string $payment_status;

    public string $raw;

    public IpnValidationEnum $validation;

    public function __construct(\app\domain\Ipn $ipn) {
        $this->id = $ipn->id;
        $this->created = $ipn->created;
        $this->validation = IpnValidationEnum::tryFrom($ipn->validation);
        $this->payment_status = $ipn->payment_status;
        $this->payment_amount = $ipn->payment_amount;
        $this->payment_currency = $ipn->payment_currency;
        $this->payer_email = $ipn->payer_email;
        $this->item_name = $ipn->item_name;
        $this->item_number = $ipn->item_number;
        $this->raw = $ipn->raw;
    }
}
