<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class Key {
    public string $created;

    public string $expires;
    public int $id;

    public string $key;

    public string $notes;

    public KeyTypeEnum $type;

    public int $userid;

    public function __construct(\app\domain\Key $key) {
        $this->id = $key->id;
        $this->userid = $key->userid;
        $this->type = KeyTypeEnum::tryFrom($key->type);
        $this->key = $key->key;
        $this->created = $key->created;
        $this->notes = $key->notes;
        $this->expires = $key->expires;
    }
}
