<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
enum KeyTypeEnum {
    case api;
    case github;
    case google;
    case pin;
    case rfid;
    case slack;
    case undefined;
}
