<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

use app\utils\EnumMapper;

/** @typescript */
class Payment {
    public string $currency;

    public string $date;
    public int $id;

    public string $ip;

    public string $item_name;

    public string $item_number;

    public int $membership_id;

    public string $payer_email;

    public string $payer_fname;

    public string $payer_lname;

    public PaymentPpEnum $pp;

    public string $rate_amount;

    public int $status;

    public string $txn_id;

    public int $user_id;

    public function __construct(\app\domain\Payment $payment) {
        $this->id = $payment->id;
        $this->txn_id = $payment->txn_id;
        $this->membership_id = $payment->membership_id;
        $this->user_id = $payment->user_id;
        $this->payer_email = $payment->payer_email;
        $this->payer_fname = $payment->payer_fname;
        $this->payer_lname = $payment->payer_lname;
        $this->rate_amount = $payment->rate_amount;
        $this->currency = $payment->currency;
        $this->date = $payment->date;
        $this->pp = EnumMapper::tryFrom(PaymentPpEnum::cases(), $payment->pp);
        $this->ip = $payment->ip;
        $this->status = $payment->status;
        $this->item_name = $payment->item_name;
        $this->item_number = $payment->item_number;
    }
}
