<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class RefreshToken {
    public int $appclientid;

    public string $expires;
    public int $id;

    public string $token;

    public int $userid;

    public function __construct(\app\domain\RefreshToken $refreshToken) {
        $this->id = $refreshToken->id;
        $this->token = $refreshToken->token;
        $this->expires = $refreshToken->expires;
        $this->userid = $refreshToken->userid;
        $this->appclientid = $refreshToken->appclientid;
    }
}
