<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
class StripeEvent {
    public string $api_version;

    public int $created;

    public string $event_id;
    public int $id;

    public string $object;

    public string $raw;

    public string $request;

    public StripeEventStatusEnum $status;

    public string $ts;

    public string $type;

    public function __construct(\app\domain\StripeEvent $stripeEvent) {
        $this->id = $stripeEvent->id;
        $this->ts = $stripeEvent->ts;
        $this->status = StripeEventStatusEnum::tryFrom($stripeEvent->status);
        $this->created = $stripeEvent->created;
        $this->event_id = $stripeEvent->event_id;
        $this->type = $stripeEvent->type;
        $this->object = $stripeEvent->object;
        $this->request = $stripeEvent->request;
        $this->api_version = $stripeEvent->api_version;
        $this->raw = $stripeEvent->raw;
    }
}
