<?php

// WARNING:
// This file is automatically generated.
// Do not edit manually.

namespace app\dto;

/** @typescript */
enum UserActiveEnum: string {
    case ACTIVE = 'y';
    case BANNED = 'b';
    case INACTIVE = 'n';
    case PENDING = 't';
}
