/* eslint-disable @typescript-eslint/max-params */
/* eslint-disable @typescript-eslint/naming-convention */
// This file was generated by generate-providers-types.sh on Wed Feb  5 22:40:41 UTC 2025.
// Do not change manually.

import type { BackendResult } from '@/types/custom'
import type { Ipn } from '@/types/records'

export interface IIpnService2 {
    /**
     * @permission administrator
     *
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {number}
     */
    CountRecords: (filters: string) => BackendResult<number>

    /**
     * @permission administrator
     *
     * @param {number} $ipnId
     *
     * @throws {string}
     *
     * @returns {Ipn}
     */
    Get: (ipnId: number) => BackendResult<Ipn>

    /**
     * @permission administrator
     *
     * @throws {string}
     *
     * @returns {Ipn[]}
     */
    GetAll: () => BackendResult<Ipn[]>

    /**
     * @permission administrator
     *
     * @param {number} $page
     * @param {number} $size
     * @param {string} $columns
     * @param {string} $order
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {Ipn[]}
     */
    ListRecords: (page: number, size: number, columns: string, order: string, filters: string) => BackendResult<Ipn[]>
}
