/* eslint-disable @typescript-eslint/naming-convention */
// This file was generated by generate-provider-types.sh on Tue Mar  4 00:14:16 UTC 2025.
// Do not change manually.

import type { BackendResult } from '@/types/api'
import type { Users } from '@/types/validators/records'

export interface IMetricService2 {
    /**
     * @permission user
     *
     * @param {string} start_range
     * @param {string} end_range
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetCreatedDates: (start_range: string, end_range: string) => BackendResult<unknown>

    /**
     * @permission administrator
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetExceptionPayments: () => BackendResult<unknown>

    /**
     * @permission user
     *
     * @param {string}                     start_range
     * @param {string}                     end_range
     * @param {"all"|"day"|"month"|"year"} group
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetMembers: (
        start_range: string,
        end_range: string,
        group: 'all' | 'day' | 'month' | 'year'
    ) => BackendResult<unknown>

    /**
     * @permission user
     *
     * @param {string} start_range string iso date in UTC, if empty is start of today
     * @param {string} end_range   string iso date in UTC, if empty is end of today
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetNewKeyHolders: (start_range: string, end_range: string) => BackendResult<unknown>

    /**
     * @permission user
     *
     * @param {string} start_range string iso date in UTC, if empty is start of today
     * @param {string} end_range   string iso date in UTC, if empty is end of today
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetNewMembers: (start_range: string, end_range: string) => BackendResult<unknown>

    /**
     * @permission administrator
     *
     * @throws {string}
     *
     * @returns {Users}
     */
    GetPendingAccounts: () => BackendResult<Users>

    /**
     * @permission user
     *
     * @param {string}                     start_range string iso date in UTC, if empty is end of today
     * @param {string}                     end_range   string iso date in UTC, if empty is end of today
     * @param {"all"|"day"|"month"|"year"} group       group by month, day, year
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetRevenue: (
        start_range: string,
        end_range: string,
        group: 'all' | 'day' | 'month' | 'year'
    ) => BackendResult<unknown>

    /**
     * @permission user
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetTotalKeyHolders: () => BackendResult<unknown>

    /**
     * @permission user
     *
     * @throws {string}
     *
     * @returns {unknown}
     */
    GetTotalMembers: () => BackendResult<unknown>
}
