/* eslint-disable @typescript-eslint/max-params */
/* eslint-disable @typescript-eslint/naming-convention */
// This file was generated by generate-providers-types.sh on Wed Feb  5 22:40:42 UTC 2025.
// Do not change manually.

import type { BackendResult } from '../custom'
import type { Payment } from '../records'

export interface IPaymentService2 {
    /**
     * @permission administrator|user
     *
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {number}
     */
    CountPayments: (filters: string) => BackendResult<number>

    /**
     * @permission administrator|user
     *
     * @param {number}    $userid
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {number}
     */
    CountUserPayments: (userid: number, filters: string) => BackendResult<number>

    /**
     * @permission administrator|user
     *
     * @param {number} $id
     *
     * @throws {string}
     *
     * @returns {Payment|null}
     */
    GetPayment: (id: number) => BackendResult<Payment | null>

    /**
     * @permission administrator
     *
     * @param {number}    $page
     * @param {number}    $size
     * @param {string} $columns
     * @param {string} $order
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {Payment[]}
     */
    ListPayments: (
        page: number,
        size: number,
        columns: string,
        order: string,
        filters: string
    ) => BackendResult<Payment[]>

    /**
     * @permission administrator|user
     *
     * @param {number}    $userid
     * @param {number}    $page
     * @param {number}    $size
     * @param {string} $columns
     * @param {string} $order
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {Payment[]}
     */
    ListUserPayments: (
        userid: number,
        page: number,
        size: number,
        columns: string,
        order: string,
        filters: string
    ) => BackendResult<Payment[]>

    /**
     * @permission administrator
     *
     * @param {number} $paymentid
     *
     * @throws {string}
     *
     * @returns {string}
     */
    ReplayPaymentProcessing: (paymentid: number) => BackendResult<string>
}
