/* eslint-disable @typescript-eslint/max-params */
/* eslint-disable @typescript-eslint/naming-convention */
// This file was generated by generate-providers-types.sh on Wed Feb  5 22:40:42 UTC 2025.
// Do not change manually.

import type { BackendResult } from '@/types/custom'
import type { StripeEvent } from '@/types/records'

export interface IStripeEventService2 {
    /**
     * @permission administrator
     *
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {number}
     */
    CountRecords: (filters: string) => BackendResult<number>

    /**
     * @permission administrator
     *
     * @param {number} $eventId
     *
     * @throws {string}
     *
     * @returns {StripeEvent}
     */
    Get: (eventId: number) => BackendResult<StripeEvent>

    /**
     * @permission administrator
     *
     * @throws {string}
     *
     * @returns {StripeEvent[]}
     */
    GetAll: () => BackendResult<StripeEvent[]>

    /**
     * @permission administrator
     *
     * @param {number}    $page
     * @param {number}    $size
     * @param {string} $columns
     * @param {string} $order
     * @param {string} $filters
     *
     * @throws {string}
     *
     * @returns {StripeEvent[]}
     */
    ListRecords: (
        page: number,
        size: number,
        columns: string,
        order: string,
        filters: string
    ) => BackendResult<StripeEvent[]>
}
