#!/usr/bin/env sh

cd "$(dirname "$(realpath "$0")")/../" || exit 255

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

if [ "${FILES}" != "" ]; then
    PHP_FILES=$(echo "${FILES}" | grep '\.php' | xargs)
    VALIDATOR_FILES=$(echo "${FILES}" | grep -E 'packages/frontend-react/src/lib/validators/(common|records).ts' | xargs)
    WEBHOOKER_FILES=$(echo "${FILES}" | grep 'packages/webhooker/' | xargs)

    if [ "${PHP_FILES}" != "" ]; then
        FILES=$(echo "${PHP_FILES}" | xargs) pnpm exec just format php
        pnpm exec just test php
    fi

    if [ "${VALIDATOR_FILES}" != "" ]; then
        pnpm exec just update validators
    fi

    if [ "${WEBHOOKER_FILES}" != "" ]; then
        pnpm exec just test webhooker
    fi

    FILES=$(echo "${FILES}" | xargs) pnpm exec just format all

    git update-index --again

    exit 0
fi
